# Generated by Django 5.1.4 on 2024-12-25 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Definition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                ("definition", models.TextField(blank=True, max_length=300)),
                (
                    "pub_date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime.now,
                        verbose_name="Date created at",
                    ),
                ),
                ("creator", models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
