# Generated by Django 4.2.20 on 2025-04-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0002_definition_downvotes_definition_example_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
